version: '3.9'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mosquitto
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/plants

  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plants
    ports:
      - "5432:5432"

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
